apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: ray-job-single
  namespace: ray-system
spec:
  entrypoint: python /workspace/simple-ml-training.py --n-samples 10000 --n-estimators 150 --max-depth 12 --output-dir /models
  shutdownAfterJobFinishes: true
  ttlSecondsAfterFinished: 60
  activeDeadlineSeconds: 600
  rayClusterSpec:
    rayVersion: '2.49.0'
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
        num-cpus: '2'
        memory: '2000000000'  # 2GB
      serviceType: ClusterIP
      template:
        metadata:
          labels:
            app: ray-head
        spec:
          containers:
          - name: ray-head
            image: rayproject/ray:2.49.0-py311-cpu
            imagePullPolicy: Always
            ports:
            - containerPort: 6379
              name: gcs-server
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            resources:
              limits:
                cpu: "2"
                memory: 2Gi
              requests:
                cpu: "1"
                memory: 1Gi
            volumeMounts:
            - name: model-cache
              mountPath: /models
            - name: ml-training-script
              mountPath: /workspace
            env:
            - name: RAY_DISABLE_IMPORT_WARNING
              value: "1"
            command: ["/bin/bash", "-lc", "--"]
            args: ["pip install -U pip && pip install pandas scikit-learn joblib && $KUBERAY_GEN_RAY_START_CMD"]
          volumes:
          - name: model-cache
            emptyDir: {}
          - name: ml-training-script
            configMap:
              name: ml-training-script
  submissionMode: K8sJobMode
  submitterPodTemplate:
    spec:
      restartPolicy: Never
      containers:
      - name: ray-job-submitter
        image: rayproject/ray:2.49.0-py311-cpu
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        volumeMounts:
        - name: model-cache
          mountPath: /models
        - name: ml-training-script
          mountPath: /workspace
        env:
        - name: RAY_DISABLE_IMPORT_WARNING
          value: "1"
      volumes:
      - name: model-cache
        emptyDir: {}
      - name: ml-training-script
        configMap:
          name: ml-training-script
